#!/bin/bash

if ! command -v "pip" >/dev/null 2>&1; then
  echo 'Pip not installed, please install to use this script';
  exit 1;
fi

if [ ! -d venv ]; then
  echo Setup venv
  python3 -m venv venv
fi
echo Changing env
source venv/bin/activate
echo Running Flask
#flask run 
python3 webapp/__init__.py
